devPackages/fieldSetForm/objects/Application_Display_Field_Logic__c.object
<CustomObject>
    <fields>
        <fullName>ControllingField_API__c</fullName>
        <label>ControllingField API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ControllingField_Object__c</fullName>
        <label>ControllingField_Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ControllingField_Value__c</fullName>
        <label>ControllingField_Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Controlling_Field_Match_Type__c</fullName>
        <label>Controlling Field Match Type</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Null</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Controlling_Field_Type__c</fullName>
        <label>Controlling Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text/Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DependentField_API__c</fullName>
        <label>DependentField_API</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Application Display Field Logic</label>
    <nameField>
        <displayFormat>DFL-{000000}</displayFormat>
        <label>Application Display Field Logic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Display Field Logic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devPackages/fieldSetForm/objects/FSF_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Credential_Name__c</fullName>
        <label>Credential Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Field Set Form Settings</label>
</CustomObject>

devPackages/fieldSetForm/classes/TestUtils.cls
@isTest
public with sharing class TestUtils {

  private static Integer uniqueNumber = 0;

  public static Account createAccount() {
    return new Account(
      Name = 'Test' + getUnique());
  }


  public static FSF_Settings__c createFSFSettings(String cName) {
    return new FSF_Settings__c(
      Credential_Name__c = cName);
  }

   public static Application_Display_Field_Logic__c
      createApplicationDisplayLogic(
        String objectName, String controllingField, String dependedField,
          String values) {
    return new Application_Display_Field_Logic__c(
      ControllingField_Object__c = objectName,
      ControllingField_API__c = controllingField,
      DependentField_API__c = dependedField,
      ControllingField_Value__c = values,
      Controlling_Field_Match_Type__c = 'Equals',
      Controlling_Field_Type__c = 'Text/Picklist');
  }

  public static String getUnique() {
    return String.valueOf(uniqueNumber++) + '_' + System.now().millisecond();
  }
}